name: ishq
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

#------------------------ PACKAGES ------------------------# 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6


# State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.7.0


# Storage Packages 
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  get_storage: ^2.1.1
  hive_flutter:


# Utility Packages
  accordion: ^2.6.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  bottom_picker: ^2.8.0
  fpdart: ^1.1.0
  country_state_city_pro: ^0.0.6
  flutter_floating_bottom_bar: ^1.2.0
  flutter_native_splash: any 
  card_swiper : ^3.0.0
  glass: ^2.0.0+1
  buttons_tabbar: ^1.3.13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  syncfusion_flutter_sliders: ^26.2.7
  multi_dropdown: any
  


#---------------------- DEV PACKAGES ----------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true


#----------------------- LOCAL ASSETS ----------------------#
  assets:
        - assets/logos/
        - assets/images/
        - assets/images/temp/
        - assets/images/default/


#----------------------- LOCAL FONTS -----------------------#
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
