// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOPo7wLkd0jUAVukSo3RtNt7xPH91IFU',
    appId: '1:1087311522136:web:665c1c4ed6908262cb1d2d',
    messagingSenderId: '1087311522136',
    projectId: 'ishq-askhalan',
    authDomain: 'ishq-askhalan.firebaseapp.com',
    storageBucket: 'ishq-askhalan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pVT1a793gGTzcW_IgUJYVh1lY3Y7Qso',
    appId: '1:1087311522136:android:c8bbc7ac465cffb4cb1d2d',
    messagingSenderId: '1087311522136',
    projectId: 'ishq-askhalan',
    storageBucket: 'ishq-askhalan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7k_HEQMZmTWALcabaJEcdjZuUIb4wORo',
    appId: '1:1087311522136:ios:2bdd39f0d8e3ff36cb1d2d',
    messagingSenderId: '1087311522136',
    projectId: 'ishq-askhalan',
    storageBucket: 'ishq-askhalan.appspot.com',
    iosBundleId: 'com.example.ishq',
  );
}
